export const experience = [
  {
    company: "Telesure Investment Holdings",
    shortName: "TIH",
    title: "Senior AI/Platform Engineer",
    period: "Aug 2025 - Present",
    note: "Permanent employee since 1 May 2026. Contractor via DotCom Software Solutions from Aug 2025 to Apr 2026",
    responsibilities: [
      "Architected and built an agentic AI framework of 18 Python packages and 17 .NET projects, applying iDesign methodology with strict dependency direction and protocol-based dependency inversion",
      "Exposed the Python framework to .NET through a gRPC sidecar with typed client libraries, so behaviour is written once",
      "Designed and built production RAG pipelines with hybrid retrieval, hierarchical summarization, and hallucination detection",
      "Implemented agentic planning and orchestration patterns including ReAct, Plan-Execute, and Adaptive strategy selection",
      "Applied enterprise security patterns: multi-turn attack detection, prompt injection defense, risk-based capability restriction",
      "Integrated multiple LLM and embedding providers with factory-based routing and graceful degradation",
      "Built a multi-bot chatbot platform: a FastAPI service with more than 100 endpoints, a React chat widget library, and an embeddable assistant",
      "Built a self-service administration portal for bot lifecycle management, knowledge versioning, and deployment orchestration",
      "Built multi-agent systems on the A2A protocol: code and documentation review agents, an agent that builds agents, a planner and proof gate, and a use-case triage and SDLC document pipeline",
      "Built a terminal AI coding assistant with permission-gated tools, persistent memory, and a VS Code extension host",
      "Built a suite of MCP servers for Azure DevOps, Microsoft Teams, Microsoft To Do, Databricks, Toggl Track and web research, with human approval for writes",
      "Authored an MCP server framework for .NET (now discontinued), then led its retirement in favour of the official C# MCP SDK and migrated the servers to .NET 10",
      "Designed and built a governed AI gateway on .NET 10 with per-application permissions, budgets, usage metering and audit",
      "Built shared Microsoft Entra authentication libraries with ten credential strategies and a coalescing token refresh service",
      "Architected and designed an agentic knowledge ingestion and curation pipeline: an orchestrator and four single-purpose agents keep assistant knowledge bases current, with a fail-closed sensitive-data gate and human review through pull requests",
      "Ran an automated CI/CD control review across more than 1,000 repositories against 17 fixed checks",
      "Designed observability infrastructure with structured logging, correlation IDs, and A/B testing metrics",
      "Wrote the developer onboarding course for the framework: an eight-chapter guide with test-graded exercises",
      "Leading technical architecture decisions and mentoring team members on AI/ML and clean architecture best practices",
    ],
  },
  {
    company: "Derivco",
    title: "Senior Software Developer",
    period: "Nov 2018 - Jun 2025",
    responsibilities: [
      "Led internal AI initiative with dynamic prompt generation for OpenAI API integration",
      "Architected LLM-powered automation tools for SDET and code review workflows",
      "Applied iDesign architectural methodology for maintainable backend systems",
      "Led technical development, release, and maintenance of end-to-end software systems in the online gaming industry",
      "Drove CI/CD pipelines (TeamCity, Octopus Deploy) and technical roadmap for multiple products",
      "Assessed complexity, scope, risk, and engineering effort for significant software development projects",
      "Contributed to architecture roadmaps, ensuring adherence to iDesign decomposition and layering principles",
      "Mentored junior developers",
    ],
  },
  {
    company: "Dynamic Visual Technologies (DVT)",
    shortName: "DVT",
    title: "Senior Software Developer GMIC.Net (Consultant)",
    period: "May 2016 - Nov 2018",
    responsibilities: [
      "Developed features and bug fixes on the GMIC.Net enterprise platform serving the mining and minerals industry",
      "Managed CI/CD build processes on client-hosted infrastructure",
      "Handled branch and release management with Git using feature, release, and hotfix branching strategy",
      "Executed system integrations between GMIC.Net and third-party systems at client sites",
      "Participated in technical discussions and design sessions relating to product development",
    ],
  },
  {
    company: "Seecrypt",
    title: "Software Developer / Team Lead",
    period: "Jun 2015 - Apr 2016",
    responsibilities: [
      "Windows team lead for the SC3 encrypted communications application (voice, messaging, file transfer)",
      "Development in C# and C++ with WPF desktop UI and Silverlight cross-platform client",
      "Implemented encrypted local storage using SQLite-SQLCipher with AES-256 encryption",
      "Managed CI/CD with Bamboo build server and Stash (Bitbucket) for Git hosting, releasing to Windows Store",
      "Led the Windows team coordinating with scrum master, product owner, and QA",
    ],
  },
  {
    company: "Covariant Consulting",
    title: "Director",
    period: "Jul 2014 - May 2015",
    responsibilities: [
      "UDCS system design and implementation for dealer network management",
      "Integration of UDCS front-ends and back-ends into Syspro ERP for finance, inventory, and reporting",
      "Business operations and client management",
    ],
  },
  {
    company: "UD Trucks",
    title: "Software Developer",
    period: "Nov 2012 - Jun 2014",
    responsibilities: [
      "Designed and implemented the UDCS system architecture for dealer customer service operations",
      "Integrated UDCS with Syspro ERP for finance, inventory, and reporting",
      "Full-stack implementation: database, data access, business logic, and front-end",
      "Managed deployment and verification after QA sign-off, maintained software and provided dealer support",
    ],
  },
  {
    company: "Enermatics",
    title: "Software Developer",
    period: "Apr 2011 - Oct 2012",
    responsibilities: [
      "Designed and implemented the Wattkeeper energy management system for monitoring electrical consumption",
      "Implemented device communication protocols for energy monitoring hardware (serial and TCP/IP)",
      "Managed deployment and verification using Hudson build server (CI/CD)",
      "Assisted with client queries and billing cycles",
    ],
  },
  {
    company: "Infotech",
    title: "Software Developer",
    period: "Sep 2009 - Mar 2011",
    responsibilities: [
      "Initial development of the Wattkeeper energy management platform (later continued at Enermatics)",
      "Implemented device communication protocols for energy monitoring hardware",
      "Managed deployment and verification using Hudson build server",
    ],
  },
  {
    company: "Information Trade World",
    shortName: "ITW",
    title: "Programmer",
    period: "Jul 2007 - Aug 2009",
    responsibilities: [
      "Desktop application development in Visual Basic and Delphi with database-driven business applications",
      "Mainframe COBOL development: batch processing, report generation, and data transformation",
      "Website development and client system management",
    ],
  },
];
